import React from 'react';
import { Box, Color } from 'ink';
import Spinner from 'ink-spinner';

// Api
import { getWeatherByCity, WeatherData } from '../api';

// Entities
import getConfig from '../config';
import getCondition from '../conditions';

// Components
import Temperature from '../Temperature';
import Direction from '../Direction';
import Ascii from '../conditions/Ascii';

interface State {
  weather: WeatherData;
  loading: boolean;
}

interface Props {
  readonly city: string;
}

class Climma extends React.Component<Props> {
  state: State = {
    weather: {},
    loading: true,
  };

  constructor(props: { city: string }) {
    super(props);

    this.fetchData = this.fetchData.bind(this);
  }

  componentDidMount() {
    this.fetchData();
  }

  async fetchData() {
    const { config } = await getConfig();
    const key = config ? config.API_KEY : undefined;

    const response = await getWeatherByCity({ key, city: this.props.city });
    this.setState({
      loading: false,
      weather: response,
    });
  }

  render() {
    const { city } = this.props;
    const { weather, loading } = this.state;

    if (loading) {
      return (
        <Box>
          <Color green>
            Loading
            <Spinner type="dots" />
          </Color>
        </Box>
      );
    }

    return (
      <Box flexDirection="column">
        <Box flexDirection="row">
          <Box flexDirection="column" marginLeft={1}>
            <Box marginBottom={1}>
              Weather for{' '}
              <Color green bold>
                {city}
              </Color>
            </Box>
            <Box>{getCondition(weather.weatherId).condition}</Box>
            <Box>
              <Temperature temp={weather.minTemperature} /> -{' '}
              <Temperature temp={weather.maxTemperature} />
            </Box>
            <Box>
              <Direction deg={weather.windDegree} /> {weather.windSpeed} km/h
            </Box>
            <Box marginBottom={1}>{weather.rain}mm</Box>
            <Box>
              <Color green>
                Weather generated by <Color bold>climma</Color>
              </Color>
            </Box>
          </Box>
          <Box marginTop={1}>
            <Ascii id={weather.weatherId} />
          </Box>
        </Box>
      </Box>
    );
  }
}

export default Climma;
