import React from 'react'
import { Box, Text, StdinContext, Color } from 'ink'
import Spinner from 'ink-spinner'

import { getWeatherByCity } from '../api'
import getConfig from '../config'
import temperatureColor from '../temperature'
import getCondition, { Conditions } from '../conditions'
import direction from '../direction'

type WeatherData = {
  weatherId?: number;
  windDegree?: number;
  windSpeed?: number;
  minTemperature?: number;
  maxTemperature?: number;
  rain?: number;
  city?: string;
}

interface State {
  weather: WeatherData;
  loading: boolean;
}

interface Props {
  readonly city: string;
}


const Ascii = () => {
  return (
    <Box flexDirection="column">
      <Box><Color yellow>{"  \\   /  "}</Color></Box>
      <Box><Color yellowBright>{"   .-.   "}</Color></Box>
      <Box><Color yellowBright>{"- (   ) -"}</Color></Box>
      <Box><Color yellowBright>{"   `-᾿   "}</Color></Box>
      <Box><Color yellow>{"  /   \\ "}</Color></Box>  
    </Box>
  )
}

const Temperature = ({temp}: {temp?: number}) => {
  if (temp === undefined) {
    return <Color ansi256={203}>{temp} °C</Color>
  }

  const n = temperatureColor(temp)
  return <Color ansi256={n}>{temp} °C</Color>
}

class Climma extends React.Component<Props> {

  state: State = {
    weather: {},
    loading: true
  }

  constructor(props: {city: string}) {
    super(props)

    this.fetchData = this.fetchData.bind(this)
  }

  async fetchData() {
    const { config } = await getConfig()
    const key = config ? config.API_KEY : undefined

    const response = await getWeatherByCity({key, city: this.props.city})
    this.setState({
      loading: false,
      weather: response
    })
  }

  componentDidMount() {
    this.fetchData()
  }

  render() {
    const { city } = this.props
    const { weather, loading } = this.state

    if (loading) {
      return (
        <Box>
          <Color green>Loading <Spinner type="dots" /></Color>
        </Box>
      )
    }

    return (
      <Box flexDirection="column">
        <Box flexDirection="row">
          <Box flexDirection="column" marginLeft={1}>
            <Box marginBottom={1}>Weather for <Color green bold>{city}</Color></Box>
            <Box>{getCondition(weather.weatherId).condition}</Box>
            <Box>
              <Temperature temp={weather.minTemperature}/> - <Temperature temp={weather.maxTemperature}/>
            </Box>
            <Box>{direction(weather.windDegree)} {weather.windSpeed} km/h</Box>
            <Box marginBottom={1}>{weather.rain}mm</Box>
            <Box>
              <Color green>Weather generated by <Color bold>climma</Color></Color>
            </Box>
          </Box>
          <Box marginTop={1}><Ascii /></Box>
        </Box>
      </Box>
    )
  }
}

export default Climma
