import dotenv from 'dotenv'

dotenv.config()

import chalk from 'chalk'

import { getWeatherByCity } from './api'
import conditions, { Conditions } from './conditions'
 
async function main() {
  const [city] = process.argv.slice(2)

  if (city === undefined) {
    console.error(chalk.red('City must be provided!'))
    throw new Error('City must be provided')
  }

  const response = await getWeatherByCity({key: process.env.API_KEY, city})
  const weatherId: keyof Conditions = response.data.weather[0].id

  console.log(chalk.green(`Weather for ${city}`))
  console.log(chalk.green(`${conditions[weatherId]}`))
  console.log(chalk.green(`Min Temperature: ${response.data.main.temp_min} °C | Max Temperature: ${response.data.main.temp_max} °C`))
  console.log(chalk.green(`Wind Speed: ${response.data.wind.speed}`))
  console.log(chalk.green(`Weather generated by ${chalk.bold(`climma`)}`))
}

main().catch(error => console.log(error))
